In [2]:
import numpy as np


In [3]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

ЗАДАНИЕ ПО NUMPY

Создаnm одномерный массив из чисел от 0 до 9 с помощью numpy.arange().

In [13]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Имея массив arr = np.array([10, 20, 30, 40, 50]), сделать срез, который вернет элементы с индексами 1, 2 и 3.

In [12]:
arr = np.array([10, 20, 30, 40, 50])
arr[1:4]

array([20, 30, 40])

 Создать массив из 12 элементов, заполненный нулями. Затем преобразовать его в массив размером 3x4 с помощью np.reshape().

In [23]:
arr = np.zeros(12)
arr
arr_2 = arr.reshape(3, 4)
arr_2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Создать массив a = np.array([1, 2, 3]) и массив b = np.array([4, 5, 6]). Найти их сумму, разность и произведение

In [30]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print('Сумма равна', sum(a + b))
print('Разность равна', sum(b) - sum(a))
print('Произведение равно', sum(a) * sum(b))

Сумма равна 21
Разность равна 9
Произведение равно 90


Создать массив arr = np.array([1, 2, 3, 4, 5]) и используй булевы индексы, чтобы получить элементы, большие 2.

In [34]:
arr = np.array([1, 2, 3, 4, 5])
arr[arr > 2]

array([3, 4, 5])

Создать двумерный массив 2x3, затем транспонировать его с помощью метода transpose() или .T.

In [110]:
arr = np.arange(6).reshape(2, 3).transpose()
arr

array([[0, 3],
       [1, 4],
       [2, 5]])

Создать два массива: a = np.array([1, 2, 3]) и b = np.array([4, 5, 6]). Объединить их в один массив с помощью np.concatenate().

In [45]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
arr = np.concatenate((a, b))
arr

array([1, 2, 3, 4, 5, 6])

Создать массив с целыми числами arr = np.array([1, 2, 3]), затем преобразовать его в массив с плавающими числами.

In [49]:
arr = np.array([1, 2, 3])
arr = arr.astype(float)
arr

array([1., 2., 3.])

Создать массив arr = np.array([5, 10, 3, 8, 1]) и найти его максимальное значение с помощью np.max()

In [52]:
arr = np.array([5, 10, 3, 8, 1])
maximum = np.max(arr)
print(maximum)

10


Сгенерировать массив из 10 случайных чисел от 0 до 1 с помощью np.random.rand() и вычислить их среднее значение.

In [75]:
arr = np.random.rand(10)
print(np.mean(arr))

0.5053815528349019


 Создать два массива: A (размером 3x2) и B (размером 2x3). Произвести матричное умножение A на B с помощью np.dot() или @

In [81]:
A = np.array([1, 2, 3, 4, 5, 6]).reshape(3, 2)
B = np.array([7, 8, 9, 10, 11, 12]).reshape(2, 3)
print(np.dot(A, B))


[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]


 Создать 5x5 матрицу с случайными числами от 0 до 1. Вычислить среднее значение по каждому столбцу.

In [88]:
arr = np.random.rand(25).reshape(5, 5)
print(np.mean(arr, axis = 0))

[0.49399551 0.39150204 0.59417568 0.73977254 0.2352654 ]


Создать 2D массив (например, 4x4), заполненный числами от 1 до 16. Написать функцию, которая поворачивает его на 90 градусов по часовой стрелке.

In [148]:
arr = np.arange(1, 17).reshape(4, 4)
print(arr)
stroka_1 = arr[0].reshape(4, 1)
stroka_2 = arr[1].reshape(4, 1)
stroka_3 = arr[2].reshape(4, 1)
stroka_4 = arr[3].reshape(4, 1)
arr_90 = np.concatenate((stroka_4, stroka_3, stroka_2, stroka_1), axis = 1)
arr_90

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


array([[13,  9,  5,  1],
       [14, 10,  6,  2],
       [15, 11,  7,  3],
       [16, 12,  8,  4]])